nelmio_api_doc:
    documentation:
        info:
            title: FiareAds 6.0 API
            version: 1.0.0
            description: |

                # Authentication

                Authentication for registries is handled client side.
                ```
                {
                  "token": "9cbaf023786cd7..."
                }
                ```

                # Errors

                The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:

                ```
                {
                  "message": "page not found"
                }
                ```

                # Staus code

                HTTP defines over 40 standard status codes that can be used to convey the results of a client’s request. The status codes are divided into the five categories presented here:


                  ##### 1xx: Informational - Communicates transfer protocol-level information

                  ##### 2xx: Success -Indicates that the client’s request was accepted successfully.
                  1. 200 OK
                  2. 201 Created
                  3. 202 Accepted
                  4. 204 No Content
                  ##### 3xx: Redirection - Indicates that the client must take some additional action in order to complete their request.
                  1. 304 Not Modified
                  ##### 4xx: Client Error - This category of error status codes points the finger at clients.
                  1. 400 Bad Request
                  2. 401 Unauthorized
                  3. 402 Payment Required
                  4. 403 Forbidden
                  5. 404 Not Found
                  6. 408 Request Timeout
                  ##### 5xx: Server Error - The server takes responsibility for these error status codes.
                  1. 500 Internal Server Error
                ```