<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => ['all' => true],
    Snc\RedisBundle\SncRedisBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    JMS\I18nRoutingBundle\JMSI18nRoutingBundle::class => ['all' => true],
    Translation\Bundle\TranslationBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Csa\Bundle\GuzzleBundle\CsaGuzzleBundle::class => ['all' => true],
    Fa\Bundle\EntityBundle\FaEntityBundle::class => ['all' => true],
    Fa\Bundle\AdminBundle\FaAdminBundle::class => ['all' => true],
    Fa\Bundle\CoreBundle\FaCoreBundle::class => ['all' => true],
    Fa\Bundle\UserBundle\FaUserBundle::class => ['all' => true],
    Fa\Bundle\ContentBundle\FaContentBundle::class => ['all' => true],
    Fa\Bundle\FixtureBundle\FaFixtureBundle::class => ['all' => true],
    Fa\Bundle\CrudBundle\FaCrudBundle::class => ['all' => true],
    Fa\Bundle\UtilityBundle\FaUtilityBundle::class => ['all' => true],
    Fa\Bundle\AuthorizationBundle\FaAuthorizationBundle::class => ['all' => true],
    Fa\Bundle\CmsBundle\FaCmsBundle::class => ['all' => true],
    Fa\Bundle\SeoBundle\FaSeoBundle::class => ['all' => true],
    Fa\Bundle\EmailBundle\FaEmailBundle::class => ['all' => true],
    Fa\Bundle\QuickLinkBundle\FaQuickLinkBundle::class => ['all' => true],
    Fa\Bundle\PluginBundle\FaPluginBundle::class => ['all' => true],
    Fa\Bundle\PromotionBundle\FaPromotionBundle::class => ['all' => true],
    Fa\Bundle\RuleBundle\FaRuleBundle::class => ['all' => true],
    Fa\Bundle\FeedbackBundle\FaFeedbackBundle::class => ['all' => true],
    Fa\Bundle\LogBundle\FaLogBundle::class => ['all' => true],
    Fa\Bundle\ItemBundle\FaItemBundle::class => ['all' => true],
    Fa\Bundle\TranslationBundle\FaTranslationBundle::class => ['all' => true],
    Fa\Bundle\BranchBundle\FaBranchBundle::class => ['all' => true],
    Fa\Bundle\ApiFieldBundle\FaApiFieldBundle::class => ['all' => true],
    Fa\Bundle\TwigBundle\FaTwigBundle::class => ['all' => true],
    Fa\Bundle\PaymentBundle\FaPaymentBundle::class => ['all' => true],
    Lexik\Bundle\TranslationBundle\LexikTranslationBundle::class => ['all' => true],
    Fa\Bundle\LexikTranslationBundle\FaLexikTranslationBundle::class => ['all' => true],
    Knp\Bundle\SnappyBundle\KnpSnappyBundle::class => ['all' => true],
    Fa\Bundle\MessageBundle\FaMessageBundle::class => ['all' => true],
    Fa\Bundle\FavoriteBundle\FaFavoriteBundle::class => ['all' => true],
    Fa\Bundle\NotificationBundle\FaNotificationBundle::class => ['all' => true],
    Fa\Bundle\SearchAgentBundle\FaSearchAgentBundle::class => ['all' => true],
    Fa\Bundle\ReportBundle\FaReportBundle::class => ['all' => true],
    Fa\Bundle\ImportExportBundle\FaImportExportBundle::class => ['all' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Fa\Bundle\LandingPageBundle\FaLandingPageBundle::class => ['all' => true],
    Fa\Bundle\ErrorBundle\FaErrorBundle::class => ['all' => true],
    Fa\Bundle\WidgetBundle\FaWidgetBundle::class => ['all' => true],
    App\Bundle\AdminBundle\AppAdminBundle::class => ['all' => true],
    App\Bundle\CoreBundle\AppCoreBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    PhpMob\TwigModifyBundle\PhpMobTwigModifyBundle::class => ['all' => true],
    Fa\Bundle\BuynowBundle\FaBuynowBundle::class => ['all' => true],
    Liip\ThemeBundle\LiipThemeBundle::class => ['all' => true],
];
